plaid/client.py, tests/test_client.py
Add support for exchange_token endpoint as documented here. https://github.com/plaid/link#exchange_token-endpoint
=> add /exchange_token endpoint support

tests/test_client.py
client.step does not exist anymore
=> fix test_step test

plaid/client.py
=> updated bad links in client

plaid/client.py, tests/integration/test_client.py
This was the one missing method I needed – should probably add the other info* methods as well but it should be trivial
=> Added info_get

README.md
location of the travis build: https://travis-ci.org/plaid/plaid-python
=> add travis testing and badge

plaid/http.py
For those who use Google App Engine
=> Map content to text attr for urlfetch response

README.md, plaid/client.py
=> Support Stripe + Plaid link exchange

plaid/client.py, tests/integration/test_client.py, tests/unit/test_client.py
=> Adding Long Tail search support

LICENSE, README.md
@chrisforrette –the Plaid team would like to thank you for your contributions to the plaid-python library.
We are simply correcting the copyright attribution to reflect that ownership. Thanks again, so much, for your contributions! We have attributed your name in the README, as noted below.
=> Update license to attribute Plaid Technologies

README.md
Highlights known issues, the issue that discusses said issue and any known work arounds.
=> Added known issues section

README.md
Closes https://github.com/plaid/plaid-python/issues/74.
=> readme: fix method calls in institutions docs

plaid/api/item.py
My bad, missed this while reviewing.
=> Remove trailing whitespace

README.md
=> Account id explanation

PUBLISH.md
- Attempt to document the module's publish process. @joyzheng and @r-ohan feedback welcome here!
=> document module publish process

plaid/requester.py
Fixes https://github.com/plaid/plaid-python/issues/106
=> add safe handling of invalid json responses

plaid/api/sandbox.py, tests/integration/test_item.py
endpoint: /sandbox/public_token/create
=> add sandbox-only endpoint

plaid/api/institutions.py, tests/integration/test_assets.py, tests/integration/test_institutions.py
/institutions/search
/institutions/get_by_id
/institutions/get
=> Add support for include_institution_data flag

docs_source/index.rst, plaid/api/item.py
Follows #155 
- Update docs to remove reference to removed methods
- Remove `Item.Credentials.update`
=> follow up #155

plaid/errors.py, tests/integration/test_item.py, tests/unit/test_errors.py
Reverts plaid/plaid-python#167
=> Revert "add item error changes for 2019-05-29 api version"

plaid/client.py, tests/integration/util.py
Similar functionality as https://github.com/plaid/plaid-node/pull/196
=> add support for client app header

README.md
=> Add documentation for versioning

plaid/api/item.py, tests/integration/test_item.py
(Tests will only pass when we introduce the field on our end)
=> Add client_user_id field to POST /item/add_token/create

plaid/errors.py, tests/integration/test_assets.py
Adds missing Plaid error classes
=> add auth_error and asset_report_error types

tests/integration/test_link_token.py
Add the language and country code fields to link/token/create test
=> add more required fields

plaid/version.py, setup.py
Docs here:
https://packaging.python.org/guides/distributing-packages-using-setuptools/
=> Updates for pypi

CHANGELOG.md, plaid/api/payment_initiation.py, tests/integration/test_payment_initiation.py
- Updates `create_payment` function to accept `options` argument
=> Adds support for new payment initiation options
