requirements.txt, setup.py
About a week ago I wasn't able to connect to Plaid using this client library anymore, I just got the following exception:
```
Traceback (most recent call last):
File "./get_transactions.py", line 40, in <module>
response = client.connect_get()
File "/.../venv/lib/python2.7/site-packages/plaid/client.py", line 50, in inner_func
return func(self, credentials, *args, **kwargs)
File "/.../venv/lib/python2.7/site-packages/plaid/client.py", line 25, in inner_func
return func(self, url, *args, **kwargs)
File "/.../venv/lib/python2.7/site-packages/plaid/client.py", line 402, in connect_get
suppress_errors=self.suppress_http_errors
File "/.../venv/lib/python2.7/site-packages/plaid/requester.py", line 14, in http_request
response = _base_http_request(url, method, data or {})
File …
```
=> Bumped requests dependency to fix SSLError

README.md
Just a tiny fix to the readme - fix typo `flakes8` to `flake8`.
=> Fix README typo: flakes8 -> flake8.

plaid/http.py
By default, App Engine's native `urlfetch` module has a deadline of 5 seconds. Since many Plaid API requests can take longer (causing the API request to fail with `DeadlineExceededException`), we increase the deadline to one minute.
This seems like a reasonable number but perhaps the Plaid team knows a better upper limit.
=> Increase App Engine urlfetch deadline

plaid/client.py, plaid/http.py, tests/integration/test_client.py
Needed these endpoints for an application I'm building so I figured I'd create and share them in Plaid's Python library. I also fixed an error in PEP-8 style that prevented "make test" from running.
=> added /info and /info/step endpoints

.gitignore, .travis.yml, requirements.txt, setup.py, tests/integration/test_client.py
The test suite would not run under python 3.5 due to pytest incompatibilities. Additionally, the travis config for this project no longer appears to be valid which this pull also corrects.
Once I had the test suite running, I discovered a bad test which was failing. I've corrected that test so that it verifies the expected behavior and passes.
=> Fix broken test suite

plaid/client.py
The readme uses the correct keyname, but the config method's docstring does not.
=> config(): correct invalid key name in docstring

.gitignore
This should fix the issue where static files weren't being loaded for the generated docs.
Per https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/.
=> Avoid having generated python docs processed by Jekyll

setup.py
Allow the use of plaid-python in projects that use requests>=2.7.0.
=> requests >= 2.7.0

plaid/client.py, plaid/requester.py
Many of the newer institutions (especially for Auth and Identity) take several minutes to receive a response.  It would be ideal for anyone consuming this API to be able to set a timeout as they would for any other request.  
This PR adds a `timeout` argument to the Client() object; all API requests are then limited to the specified timeout, else a `ReadTimeoutError` is raised.
=> Added logic for request timeouts

.gitignore
Since the static resources folder `docs/_static` starts with an `_`, we want to bypass jekyll processing for hosting: https://github.com/blog/572-bypassing-jekyll-on-github-pages.
=> Fix docs hosting

plaid/client.py, plaid/requester.py, tests/integration/util.py
Adds support for api version 2018-05-22
=> add support for version 2018-05-22

plaid/api/processor.py, tests/integration/test_processor.py
Adding support for Dwolla processor token. Mimicking code currently used for Stripe
=> Add support for Dwolla processor token

Makefile, docs_source/conf.py, plaid/api/income.py, tests/integration/test_assets.py, tests/integration/test_income.py, tests/integration/test_item.py, tests/integration/test_processor.py, tests/integration/util.py, tox.ini
Makes make test run tox, the same way our CI does. Hopefully this makes for slightly faster iterations, and could help expose issues with different python versions. 
Also adding stricter requirements in terms of test coverage and code style.
I also think this new error message is more informative for missing `.env`:
```bash
bash-3.2$ make test
flake8 plaid
./.env tox
make: ./.env: No such file or directory
make: *** [test] Error 1
```
=> Run tests locally with tox to create parity with CI. pep8 as part of tests.

plaid/api/accounts.py, plaid/api/assets.py, plaid/api/auth.py, plaid/api/institutions.py, plaid/api/item.py, plaid/api/sandbox.py, plaid/api/transactions.py
Kwargs are evaluated import time and for objects (in this case the dict) the function is passed a reference to the same dict on each call. This is an anti-pattern because it introduces state in functions in an unexpected way (if the dict is mutated then subsequent function calls are affected by this mutation too).
This change is backwards compatible and removes risk of subtle and hard-to-identify bugs.
=> Removed occurences of mutable kwargs

circle.yml, tests/integration/test_assets.py, tests/unit/test_errors.py, tox.ini
Ah, so circle was installing dependencies in a venv/ folder besides tox, which caused tests in venv to run and fail.
Also, two new modules from merge weren't linted
=> Fix build on CI

tox.ini
This is what it was before, I was using 3.7 locally.
=> run CI on python3.6

plaid/api/item.py, plaid/api/sandbox.py, tests/integration/test_accounts.py, tests/integration/test_assets.py, tests/integration/test_auth.py, tests/integration/test_credit_details.py, tests/integration/test_identity.py, tests/integration/test_income.py, tests/integration/test_item.py, tests/integration/test_transactions.py, tests/integration/util.py
- Deprecate direct integration as it is no longer supported
- Remove deprecated `/item/delete` in favor of `/item/remove`
These are both breaking changes - this will be released as a major version bump.
=> deprecate direct integration

CHANGELOG.md, PUBLISH.md
Retroactively add a changelog thru 2.4.0 and update the publishing instructions to include a reference to updating the changelog.
Closes https://github.com/plaid/plaid-python/issues/158
=> add CHANGELOG.md

plaid/api/item.py, tests/integration/test_item.py
Update the beta `/item/add_token/create` with support for additional user data, which enables more features for returning users.
=> Add support for user data in /item/add_token/create

plaid/api/institutions.py, tests/integration/test_institutions.py
Reorders the country code input to be after id and query to be consistent with other CLibs. 
Note that I can't update the `get` endpoint since `offset` is a default field and default fields must be after all other fields in python.
=> reorder country code inputs
